-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 21:18:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_flavia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_flavia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_flavia` DEFAULT CHARACTER SET utf8 ;
USE `db_flavia` ;

-- -----------------------------------------------------
-- Table `tb_persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_persons` ;

CREATE TABLE IF NOT EXISTS `tb_persons` (
  `id_person` INT(11) NOT NULL AUTO_INCREMENT,
  `des_person` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NULL DEFAULT NULL,
  `phone` BIGINT(20) NULL DEFAULT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cpf` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tb_addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_addresses` ;

CREATE TABLE IF NOT EXISTS `tb_addresses` (
  `id_address` INT(11) NOT NULL AUTO_INCREMENT,
  `id_person` INT(11) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `complement` VARCHAR(32) NULL DEFAULT NULL,
  `city` VARCHAR(32) NOT NULL,
  `state` VARCHAR(32) NOT NULL,
  `country` VARCHAR(32) NOT NULL,
  `zip_code` INT(11) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_address`),
  CONSTRAINT `fk_addresses_persons`
    FOREIGN KEY (`id_person`)
    REFERENCES `tb_persons` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_addresses_persons_idx` ON `tb_addresses` (`id_person` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tb_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_users` ;

CREATE TABLE IF NOT EXISTS `tb_users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `id_person` INT(11) NOT NULL,
  `des_login` VARCHAR(64) NOT NULL,
  `des_password` VARCHAR(256) NOT NULL,
  `inadmin` TINYINT(4) NOT NULL DEFAULT '0',
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `fk_users_persons`
    FOREIGN KEY (`id_person`)
    REFERENCES `tb_persons` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_users_persons_idx` ON `tb_users` (`id_person` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tb_carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_carts` ;

CREATE TABLE IF NOT EXISTS `tb_carts` (
  `id_cart` INT(11) NOT NULL,
  `des_session_id` VARCHAR(64) NOT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  `id_address` INT(11) NULL DEFAULT NULL,
  `vl_freight` DECIMAL(10,2) NULL DEFAULT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cart`),
  CONSTRAINT `fk_carts_addresses`
    FOREIGN KEY (`id_address`)
    REFERENCES `tb_addresses` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `tb_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_carts_users_idx` ON `tb_carts` (`id_user` ASC) VISIBLE;

CREATE INDEX `fk_carts_addresses_idx` ON `tb_carts` (`id_address` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tb_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_products` ;

CREATE TABLE IF NOT EXISTS `tb_products` (
  `id_product` INT(11) NOT NULL,
  `des_product` VARCHAR(64) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `des_url` VARCHAR(128) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tb_carts_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_carts_products` ;

CREATE TABLE IF NOT EXISTS `tb_carts_products` (
  `id_cart_product` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cart` INT(11) NOT NULL,
  `id_product` INT(11) NOT NULL,
  `dt_removed` DATETIME NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cart_product`),
  CONSTRAINT `fk_cartsproducts_carts`
    FOREIGN KEY (`id_cart`)
    REFERENCES `tb_carts` (`id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartsproducts_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `tb_products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_cartsproducts_carts_idx` ON `tb_carts_products` (`id_cart` ASC) VISIBLE;

CREATE INDEX `FK_cartsproducts_products_idx` ON `tb_carts_products` (`id_product` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tb_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_categories` ;

CREATE TABLE IF NOT EXISTS `tb_categories` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `des_category` VARCHAR(32) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tb_orders_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_orders_status` ;

CREATE TABLE IF NOT EXISTS `tb_orders_status` (
  `id_status` INT(11) NOT NULL AUTO_INCREMENT,
  `des_status` VARCHAR(32) BINARY NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tb_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_orders` ;

CREATE TABLE IF NOT EXISTS `tb_orders` (
  `id_order` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cart` INT(11) NOT NULL,
  `id_user` INT(11) NOT NULL,
  `id_status` INT(11) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_order`),
  CONSTRAINT `fk_orders_carts`
    FOREIGN KEY (`id_cart`)
    REFERENCES `tb_carts` (`id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_ordersstatus`
    FOREIGN KEY (`id_status`)
    REFERENCES `tb_orders_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `tb_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `FK_orders_carts_idx` ON `tb_orders` (`id_cart` ASC) VISIBLE;

CREATE INDEX `FK_orders_users_idx` ON `tb_orders` (`id_user` ASC) VISIBLE;

CREATE INDEX `fk_orders_ordersstatus_idx` ON `tb_orders` (`id_status` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tb_products_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_products_categories` ;

CREATE TABLE IF NOT EXISTS `tb_products_categories` (
  `id_category` INT(11) NOT NULL,
  `id_product` INT(11) NOT NULL,
  PRIMARY KEY (`id_category`, `id_product`),
  CONSTRAINT `fk_productscategories_categories`
    FOREIGN KEY (`id_category`)
    REFERENCES `tb_categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productscategories_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `tb_products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_productscategories_products_idx` ON `tb_products_categories` (`id_product` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tb_users_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_users_logs` ;

CREATE TABLE IF NOT EXISTS `tb_users_logs` (
  `id_log` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `des_log` VARCHAR(128) NOT NULL,
  `des_ip` VARCHAR(45) NOT NULL,
  `des_user_agent` VARCHAR(128) NOT NULL,
  `des_session_id` VARCHAR(64) NOT NULL,
  `des_url` VARCHAR(128) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`),
  CONSTRAINT `fk_userslogs_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `tb_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_userslogs_users_idx` ON `tb_users_logs` (`id_user` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tb_users_passwords_recoveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_users_passwords_recoveries` ;

CREATE TABLE IF NOT EXISTS `tb_users_passwords_recoveries` (
  `id_recovery` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `des_ip` VARCHAR(45) NOT NULL,
  `dt_recovery` DATETIME NULL DEFAULT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_recovery`),
  CONSTRAINT `fk_userspasswordsrecoveries_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `tb_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_userspasswordsrecoveries_users_idx` ON `tb_users_passwords_recoveries` (`id_user` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
